/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as SellRouteImport } from './routes/sell'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as R403RouteImport } from './routes/403'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as BrandSlugRouteImport } from './routes/brand.$slug'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandSlugRoute = BrandSlugRouteImport.update({
  id: '/brand/$slug',
  path: '/brand/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/brands': typeof BrandsRoute
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/sell': typeof SellRoute
  '/seller': typeof SellerRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/wishlist': typeof WishlistRoute
  '/brand/$slug': typeof BrandSlugRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/brands': typeof BrandsRoute
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/sell': typeof SellRoute
  '/seller': typeof SellerRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/wishlist': typeof WishlistRoute
  '/brand/$slug': typeof BrandSlugRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/brands': typeof BrandsRoute
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/sell': typeof SellRoute
  '/seller': typeof SellerRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/wishlist': typeof WishlistRoute
  '/brand/$slug': typeof BrandSlugRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/account'
    | '/admin'
    | '/brands'
    | '/cart'
    | '/login'
    | '/sell'
    | '/seller'
    | '/shop'
    | '/signup'
    | '/wishlist'
    | '/brand/$slug'
    | '/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/account'
    | '/admin'
    | '/brands'
    | '/cart'
    | '/login'
    | '/sell'
    | '/seller'
    | '/shop'
    | '/signup'
    | '/wishlist'
    | '/brand/$slug'
    | '/product/$id'
  id:
    | '__root__'
    | '/'
    | '/403'
    | '/account'
    | '/admin'
    | '/brands'
    | '/cart'
    | '/login'
    | '/sell'
    | '/seller'
    | '/shop'
    | '/signup'
    | '/wishlist'
    | '/brand/$slug'
    | '/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R403Route: typeof R403Route
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  BrandsRoute: typeof BrandsRoute
  CartRoute: typeof CartRoute
  LoginRoute: typeof LoginRoute
  SellRoute: typeof SellRoute
  SellerRoute: typeof SellerRoute
  ShopRoute: typeof ShopRoute
  SignupRoute: typeof SignupRoute
  WishlistRoute: typeof WishlistRoute
  BrandSlugRoute: typeof BrandSlugRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/$slug': {
      id: '/brand/$slug'
      path: '/brand/$slug'
      fullPath: '/brand/$slug'
      preLoaderRoute: typeof BrandSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R403Route: R403Route,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  BrandsRoute: BrandsRoute,
  CartRoute: CartRoute,
  LoginRoute: LoginRoute,
  SellRoute: SellRoute,
  SellerRoute: SellerRoute,
  ShopRoute: ShopRoute,
  SignupRoute: SignupRoute,
  WishlistRoute: WishlistRoute,
  BrandSlugRoute: BrandSlugRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
